In [ ]:
pip install --upgrade xgboost shap

In [ ]:
pip install scikit-multilearn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.4/89.4 kB 4.4 MB/s eta 0:00:00


# Technique

In [ ]:
import pandas as pd
import shap
from xgboost import XGBClassifier
from skmultilearn.problem_transform import LabelPowerset
from sklearn.model_selection import train_test_split
from sklearn.metrics import (classification_report, recall_score, hamming_loss, jaccard_score,
                             multilabel_confusion_matrix, f1_score, precision_score, accuracy_score,
                             zero_one_loss)
from datetime import datetime
# -*- coding: utf-8 -*-
# Importing required Library
import numpy as np
import pandas as pd
import random

# Record start time
st = datetime.now()

# Load the dataset
file_path = 'Technique_Dataset.csv'
df = pd.read_csv(file_path)

# Drop the column 'Lateral Movement'
df = df.drop(columns=['T1458','T1660','T1456','T1631','T1664','T1663','T1461','T1661','T1639','T1641','T1474','T1603','T1638'])
# Separate features and labels
X = df.iloc[:, 1:-48]
y = df.iloc[:, -48:]


In [ ]:
from sklearn.neighbors import NearestNeighbors
def get_tail_label(df):
    """
    Give tail label colums of the given target dataframe

    args
    df: pandas.DataFrame, target label df whose tail label has to identified

    return
    tail_label: list, a list containing column name of all the tail label
    """
    columns = df.columns
    n = len(columns)
    irpl = np.zeros(n)
    for column in range(n):
        irpl[column] = df[columns[column]].value_counts()[1]
    irpl = max(irpl)/irpl
    mir = np.average(irpl)
    tail_label = []
    for i in range(n):
        if irpl[i] > mir:
            tail_label.append(columns[i])
    print(tail_label)
    return tail_label

def get_index(df):
  """
  give the index of all tail_label rows
  args
  df: pandas.DataFrame, target label df from which index for tail label has to identified

  return
  index: list, a list containing index number of all the tail label
  """
  tail_labels = get_tail_label(df)
  index = set()
  for tail_label in tail_labels:
    sub_index = set(df[df[tail_label]==1].index)
    index = index.union(sub_index)
  return list(index)

def get_minority_instace(X, y):
    """
    Give minority dataframe containing all the tail labels

    args
    X: pandas.DataFrame, the feature vector dataframe
    y: pandas.DataFrame, the target vector dataframe

    return
    X_sub: pandas.DataFrame, the feature vector minority dataframe
    y_sub: pandas.DataFrame, the target vector minority dataframe
    """
    index = get_index(y)
    X_sub = X[X.index.isin(index)].reset_index(drop = True)
    y_sub = y[y.index.isin(index)].reset_index(drop = True)
    return X_sub, y_sub

def nearest_neighbour(X):
    """
    Give index of 5 nearest neighbor of all the instance

    args
    X: np.array, array whose nearest neighbor has to find

    return
    indices: list of list, index of 5 NN of each element in X
    """
    nbs=NearestNeighbors(n_neighbors=5,metric='euclidean',algorithm='kd_tree').fit(X)
    euclidean,indices= nbs.kneighbors(X)
    return indices

def MLSMOTE(X,y, n_sample):
    """
    Give the augmented data using MLSMOTE algorithm

    args
    X: pandas.DataFrame, input vector DataFrame
    y: pandas.DataFrame, feature vector dataframe
    n_sample: int, number of newly generated sample

    return
    new_X: pandas.DataFrame, augmented feature vector data
    target: pandas.DataFrame, augmented target vector data
    """
    indices2 = nearest_neighbour(X)
    n = len(indices2)
    new_X = np.zeros((n_sample, X.shape[1]))
    target = np.zeros((n_sample, y.shape[1]))
    for i in range(n_sample):
        reference = random.randint(0,n-1)
        neighbour = random.choice(indices2[reference,1:])
        all_point = indices2[reference]
        nn_df = y[y.index.isin(all_point)]
        ser = nn_df.sum(axis = 0, skipna = True)
        target[i] = np.array([1 if val>2 else 0 for val in ser])
        ratio = random.random()
        gap = X.loc[reference,:] - X.loc[neighbour,:]
        new_X[i] = np.array(X.loc[reference,:] + ratio * gap)
    new_X = pd.DataFrame(new_X, columns=X.columns)
    target = pd.DataFrame(target, columns=y.columns)
    new_X = pd.concat([X, new_X], axis=0)
    target = pd.concat([y, target], axis=0)
    return new_X, target

In [ ]:
# Get the minority instance data
X_sub, y_sub = get_minority_instace(X, y)

['T1577', 'T1624', 'T1481', 'T1471', 'T1420', 'T1544', 'T1617', 'T1640', 'T1398', 'T1421', 'T1642', 'T1662', 'T1414', 'T1509', 'T1541']


In [ ]:
def calculate_n_sample(y, target_percentage=100, max_samples=None):
    """
    Calculate the required number of synthetic samples to achieve a target
    percentage of the highest label count without exceeding the original sample count.

    Args:
    y (pd.DataFrame): The target vector dataframe with binary multi-label columns.
    target_percentage (int): Target percentage of the maximum label count
                             for balancing (e.g., 25, 50, 75, or 100).
    max_samples (int): Maximum allowable samples to generate (e.g., original dataset size).

    Returns:
    int: Total number of synthetic samples needed, capped at max_samples.
    """
    # Find the count of the most common label
    label_counts = y.sum(axis=0)
    max_count = label_counts.max()

    # Calculate the target count based on the specified percentage
    target_count = int(max_count * (target_percentage / 100))


    return target_count

In [ ]:
# Open the file and read the contents
with open('Technique_Best_100.txt', 'r') as file:
    # Read the content and split by commas
    features = file.read().split(',')

# Strip any leading or trailing whitespace from each item in the list
features = [feature.strip() for feature in features]

# Print the list
print(features)


['android.permission.uses_policy_force_lock', 'fr.devnied.currency.activity.homeactivity', 'com.mywickr.gui.login.loginregloadingactivity', 'com.tencent.mm.composesmsactivity', 'com.jeyidsmx.nqusgukvih', 'com.coincast.app.widget.widgetconfigureactivity', 'android.permission.bind_device_admin', 'com.hangoverlabs.services.recordservice', 'com.coincast.app.broadcastreceivers.autostart', 'com.tencent.mm.mainactivity', 'com.viber.voip.inject_activity', 'org.wollyrolly.core.mainactivity', 'android.media.action.video_capture', 'com.adobe.settings.gui.aup', 'com.android.servicex.receiver.powerconnectionreceiver', 'com.myapps.update.services.dcservice', 'android.permission.write_external_storage', 'homeworkout.homeworkouts.noequipment.unitactivity', 'com.facebook.unity.fbunityloginactivity', 'android.intent.category.launcher_app', 'com.gameloft.android.anmp.gloftghhm.kpm65lugdnv', 'vlhtc.hsicifsgxehymvdvajyzyckijyatpo.p033g', 'com.xbot.core.smshandler', 'com.edujoy.word_search.nydwk04efrn', 'co

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.model_selection import train_test_split
from sklearn.metrics import (classification_report, recall_score, hamming_loss, jaccard_score,
                             multilabel_confusion_matrix, f1_score, precision_score, accuracy_score,
                             zero_one_loss)
from xgboost import XGBClassifier
from skmultilearn.problem_transform import LabelPowerset
from functools import reduce
import time

# Store execution times for each value of k
execution_data = []

# Get column names for X
label_names = y.columns.tolist()

# Define different random seeds to evaluate
random_seeds = [42, 1433, 2396, 451, 995, 98, 262, 354, 560, 1600]
# Function to evaluate the model
def evaluate_model(X_train, X_test, y_train, y_test, selected_features, model_name, file, random_seed,percentage):
    X_train_selected = X_train.loc[:, selected_features]
    X_test_selected = X_test.loc[:, selected_features]

    # Convert selected features to NumPy arrays
    X_train_selected = X_train_selected.values  # Convert to NumPy array
    X_test_selected = X_test_selected.values    # Convert to NumPy array

    lb_model = LabelPowerset(XGBClassifier(gamma=0,learning_rate=0.3,max_depth=6,n_estimators=100,random_state=42))
    lb_model.fit(X_train_selected, y_train)
    lb_predictions = lb_model.predict(X_test_selected)
    file.write(f"\n\n********** ML_SMOTE_PERCENTAGE: {percentage} **********\n\n")
    file.write(f"\n\n********** Random Seed: {random_seed} **********\n\n")
    file.write(f"\nEvaluating {model_name}")
    file.write(f"\nAccuracy: {accuracy_score(y_test, lb_predictions)}")
    file.write(f"\nMacro F1 Score: {f1_score(y_test, lb_predictions, average='macro')}")
    file.write(f"\nWeighted F1 score: {f1_score(y_test, lb_predictions, average='weighted')}")
    file.write(f"\nMicro F1 score: {f1_score(y_test, lb_predictions, average='micro')}")
    file.write(f"\nMacro Precision: {precision_score(y_test, lb_predictions, average='macro')}")
    file.write(f"\nWeighted Precision: {precision_score(y_test, lb_predictions, average='weighted')}")
    file.write(f"\nMicro Precision: {precision_score(y_test, lb_predictions, average='micro')}")
    file.write(f"\nMacro Recall: {recall_score(y_test, lb_predictions, average='macro')}")
    file.write(f"\nWeighted Recall: {recall_score(y_test, lb_predictions, average='weighted')}")
    file.write(f"\nMicro Recall: {recall_score(y_test, lb_predictions, average='micro')}")
    file.write(f"\nHamming Loss: {hamming_loss(y_test, lb_predictions)}")
    file.write(f"\nZero One Loss: {zero_one_loss(y_test, lb_predictions)}")
    file.write(f"\nJaccard Similarity: {jaccard_score(y_test, lb_predictions, average='samples')}")
    file.write(f"\nClassification Report:\n{classification_report(y_test, lb_predictions, target_names=label_names)}")
    file.write(f"\nMultilabel Confusion Matrix:\n{multilabel_confusion_matrix(y_test, lb_predictions)}")
    file.write("\n")

    file.write(f"\n\n********** ML_SMOTE_PERCENTAGE: {percentage} **********\n\n")
    print(f"\n\n********** Random Seed: {random_seed} **********\n\n")
    print(f"Evaluating {model_name}")
    print(f"Accuracy: {accuracy_score(y_test, lb_predictions)}")
    print(f"Macro F1 Score: {f1_score(y_test, lb_predictions, average='macro')}")
    print(f"Weighted F1 score: {f1_score(y_test, lb_predictions, average='weighted')}")
    print(f"Micro F1 score: {f1_score(y_test, lb_predictions, average='micro')}")
    print(f"Macro Precision: {precision_score(y_test, lb_predictions, average='macro')}")
    print(f"Weighted Precision: {precision_score(y_test, lb_predictions, average='weighted')}")
    print(f"Micro Precision: {precision_score(y_test, lb_predictions, average='micro')}")
    print(f"Macro Recall: {recall_score(y_test, lb_predictions, average='macro')}")
    print(f"Weighted Recall: {recall_score(y_test, lb_predictions, average='weighted')}")
    print(f"Micro Recall: {recall_score(y_test, lb_predictions, average='micro')}")
    print(f"Hamming Loss: {hamming_loss(y_test, lb_predictions)}")
    print(f"Zero One Loss: {zero_one_loss(y_test, lb_predictions)}")
    print(f"Jaccard Similarity: {jaccard_score(y_test, lb_predictions, average='samples')}")
    print(f"Classification Report:\n{classification_report(y_test, lb_predictions, target_names=label_names)}")
    print(f"Multilabel Confusion Matrix:\n{multilabel_confusion_matrix(y_test, lb_predictions)}")
    print("\n")


original_sample_count = len(y)
for percentage in [25, 50, 75, 100]:
    start_time = time.time()  # Start measuring execution time
    n_sample = calculate_n_sample(y, target_percentage=percentage, max_samples=original_sample_count)
    print(f"Number of samples to generate for {percentage}% of max count: {n_sample}")


    # Apply MLSMOTE to generate augmented data
    X_res, y_res = MLSMOTE(X_sub, y_sub, n_sample)
    print(len(X_res))

    # Dynamically create variable names and assign augmented data to them
    globals()[f"X_res_{percentage}"] = X_res
    globals()[f"y_res_{percentage}"] = y_res
    X_aug=pd.concat([X, X_res], axis=0)
    y_aug=pd.concat([y, y_res], axis=0)
    # Open a file to write evaluations for the current k value
    with open(f"Technique_ML_SMOTE_XGBoost_model_evaluations.txt", "w", encoding='utf-8') as file:
        for seed in random_seeds:
            X_train, X_test, y_train, y_test = train_test_split(X_aug, y_aug, test_size=0.2, random_state=seed)
            evaluate_model(X_train, X_test, y_train, y_test, features, "Label Powerset", file, seed,percentage)

    end_time = time.time()  # End measuring execution time
    execution_time = end_time - start_time
    # Append execution time and number of combined features to execution_data
    execution_data.append({"Percentage": percentage,"N_Sample": n_sample, "execution_time": execution_time})

# Convert execution_data to DataFrame
execution_df = pd.DataFrame(execution_data)

# Save DataFrame to CSV file
execution_df.to_csv("Technique_ML_SMOTE_execution_time.csv", index=False)

Number of samples to generate for 25% of max count: 593
867


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))




********** Random Seed: 42 **********


Evaluating Label Powerset
Accuracy: 0.9561042524005487
Macro F1 Score: 0.9715523744800617
Weighted F1 score: 0.9842242153705544
Micro F1 score: 0.984247006931317
Macro Precision: 0.9731550221900087
Weighted Precision: 0.9851355811705853
Micro Precision: 0.9850586979722519
Macro Recall: 0.9706256055793316
Weighted Recall: 0.9834366524602867
Micro Recall: 0.9834366524602867
Hamming Loss: 0.009287837219935985
Zero One Loss: 0.04389574759945125
Jaccard Similarity: 0.9680840137999139
Classification Report:
              precision    recall  f1-score   support

       T1424       0.98      0.98      0.98        48
       T1604       0.97      0.99      0.98        68
       T1532       0.92      0.92      0.92        50
       T1404       0.98      0.98      0.98       219
       T1422       0.99      0.99      0.99       448
       T1577       1.00      1.00      1.00         9
       T1437       0.98      0.98      0.98       476
       T1512      

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))




********** Random Seed: 1433 **********


Evaluating Label Powerset
Accuracy: 0.9423868312757202
Macro F1 Score: 0.9725234252098959
Weighted F1 score: 0.9822305558812816
Micro F1 score: 0.9821611846928303
Macro Precision: 0.96438779550701
Weighted Precision: 0.9785042547326812
Micro Precision: 0.9781931464174455
Macro Recall: 0.9822385073696601
Weighted Recall: 0.9861615467661203
Micro Recall: 0.9861615467661203
Hamming Loss: 0.01043095564700503
Zero One Loss: 0.057613168724279795
Jaccard Similarity: 0.9563812396713333
Classification Report:
              precision    recall  f1-score   support

       T1424       0.93      0.98      0.95        43
       T1604       1.00      0.98      0.99        62
       T1532       0.94      0.98      0.96        66
       T1404       0.97      0.99      0.98       208
       T1422       0.98      1.00      0.99       466
       T1577       1.00      1.00      1.00        20
       T1437       0.98      0.99      0.99       446
       T1512     

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))




********** Random Seed: 2396 **********


Evaluating Label Powerset
Accuracy: 0.9670781893004116
Macro F1 Score: 0.982812230120205
Weighted F1 score: 0.9895550705172915
Micro F1 score: 0.9895486935866984
Macro Precision: 0.9818605937502086
Weighted Precision: 0.9894969357156088
Micro Precision: 0.9894546836405093
Macro Recall: 0.9839781010744636
Weighted Recall: 0.9896427213987077
Micro Recall: 0.9896427213987077
Hamming Loss: 0.006287151348879744
Zero One Loss: 0.03292181069958844
Jaccard Similarity: 0.9772879571880899
Classification Report:
              precision    recall  f1-score   support

       T1424       1.00      1.00      1.00        50
       T1604       0.99      1.00      0.99        66
       T1532       0.98      0.97      0.98        66
       T1404       0.98      0.98      0.98       221
       T1422       0.99      0.99      0.99       483
       T1577       1.00      1.00      1.00        15
       T1437       0.99      0.99      0.99       476
       T1512    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))




********** Random Seed: 451 **********


Evaluating Label Powerset
Accuracy: 0.9492455418381345
Macro F1 Score: 0.9745279460985827
Weighted F1 score: 0.9849475235350025
Micro F1 score: 0.9849305047549378
Macro Precision: 0.9753486059545123
Weighted Precision: 0.987176487518786
Micro Precision: 0.9870967741935484
Macro Recall: 0.973960899396166
Weighted Recall: 0.9827737226277372
Micro Recall: 0.9827737226277372
Hamming Loss: 0.008830589849108368
Zero One Loss: 0.05075445816186552
Jaccard Similarity: 0.9630769016816328


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Classification Report:
              precision    recall  f1-score   support

       T1424       0.96      0.98      0.97        48
       T1604       1.00      1.00      1.00        74
       T1532       0.93      0.94      0.93        53
       T1404       0.97      0.97      0.97       199
       T1422       0.99      0.98      0.99       459
       T1577       1.00      1.00      1.00        20
       T1437       0.98      0.98      0.98       461
       T1512       0.99      0.98      0.99       454
       T1430       0.99      0.98      0.99       506
       T1418       0.99      0.99      0.99       489
       T1624       1.00      1.00      1.00        20
       T1645       0.99      0.98      0.99       234
       T1429       0.99      0.98      0.99       478
       T1417       0.99      0.97      0.98       224
       T1481       0.78      0.78      0.78        23
       T1426       0.99      0.98      0.99       517
       T1644       0.99      0.99      0.99       376
    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))




********** Random Seed: 262 **********


Evaluating Label Powerset
Accuracy: 0.9396433470507545
Macro F1 Score: 0.9664336317275328
Weighted F1 score: 0.9814962959564753
Micro F1 score: 0.9813754971384228
Macro Precision: 0.9549762016972911
Weighted Precision: 0.9777922984448794
Micro Precision: 0.9772990726429676
Macro Recall: 0.9795176229676027
Weighted Recall: 0.98548607052406
Micro Recall: 0.98548607052406
Hamming Loss: 0.010973936899862825
Zero One Loss: 0.060356652949245526
Jaccard Similarity: 0.9552119268886698
Classification Report:
              precision    recall  f1-score   support

       T1424       0.92      0.98      0.95        50
       T1604       1.00      1.00      1.00        61
       T1532       0.94      0.97      0.95        62
       T1404       0.98      0.99      0.98       210
       T1422       0.98      0.99      0.99       456
       T1577       1.00      1.00      1.00        11
       T1437       0.99      0.98      0.99       453
       T1512       

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))




********** Random Seed: 354 **********


Evaluating Label Powerset
Accuracy: 0.9547325102880658
Macro F1 Score: 0.9646356077601882
Weighted F1 score: 0.9876533595720112
Micro F1 score: 0.9876089060987415
Macro Precision: 0.9675002859402998
Weighted Precision: 0.9897170552181915
Micro Precision: 0.9895247332686712
Macro Recall: 0.9628562601630352
Weighted Recall: 0.9857004830917875
Micro Recall: 0.9857004830917875
Hamming Loss: 0.007315957933241884
Zero One Loss: 0.04526748971193417
Jaccard Similarity: 0.9675697144184351
Classification Report:
              precision    recall  f1-score   support

       T1424       0.90      0.92      0.91        39
       T1604       1.00      1.00      1.00        71
       T1532       0.96      0.99      0.97        69
       T1404       0.99      0.99      0.99       195
       T1422       0.99      0.99      0.99       471
       T1577       1.00      1.00      1.00        21
       T1437       0.98      0.99      0.98       457
       T1512    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 1433 **********


Evaluating Label Powerset
Accuracy: 0.9598583234946871
Macro F1 Score: 0.9864146844524061
Weighted F1 score: 0.9884773845524918
Micro F1 score: 0.9884699545531055
Macro Precision: 0.9819279334684884
Weighted Precision: 0.9859539959982043
Micro Precision: 0.9858977587509443
Macro Recall: 0.9911401582393348
Weighted Recall: 0.9910556071217619
Micro Recall: 0.9910556071217619
Hamming Loss: 0.006739472648563558
Zero One Loss: 0.04014167650531286
Jaccard Similarity: 0.9715059574073389
Classification Report:
              precision    recall  f1-score   support

       T1424       0.96      1.00      0.98        49
       T1604       0.99      0.99      0.99        70
       T1532       0.99      0.98      0.99       106
       T1404       0.98      0.98      0.98       206
       T1422       0.99      0.99      0.99       543
       T1577       1.00      1.00      1.00        31
       T1437       0.98      0.99      0.99       486
       T1512   

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/me



********** Random Seed: 2396 **********


Evaluating Label Powerset
Accuracy: 0.9527744982290437
Macro F1 Score: 0.9786705847006164
Weighted F1 score: 0.9822474917234096
Micro F1 score: 0.9822275903718403
Macro Precision: 0.9717686625173858
Weighted Precision: 0.9759800377184513
Micro Precision: 0.9758292620210851
Macro Recall: 0.986105561699255
Weighted Recall: 0.9887103777681285
Micro Recall: 0.9887103777681285
Hamming Loss: 0.010133805588351042
Zero One Loss: 0.0472255017709563
Jaccard Similarity: 0.9645827334928948
Classification Report:
              precision    recall  f1-score   support

       T1424       0.94      0.94      0.94        53
       T1604       0.97      1.00      0.99        75
       T1532       0.94      0.99      0.96        95
       T1404       0.98      0.98      0.98       200
       T1422       0.98      0.99      0.99       521
       T1577       1.00      1.00      1.00        23
       T1437       0.98      0.99      0.98       486
       T1512     

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 995 **********


Evaluating Label Powerset
Accuracy: 0.9669421487603306
Macro F1 Score: 0.9855549789477355
Weighted F1 score: 0.9893221183985045
Micro F1 score: 0.9892879647132955
Macro Precision: 0.9820484203467489
Weighted Precision: 0.9882496590792007
Micro Precision: 0.9880842493916254
Macro Recall: 0.9894352838564275
Weighted Recall: 0.9904946164199192
Micro Recall: 0.9904946164199192
Hamming Loss: 0.006272136953955136
Zero One Loss: 0.03305785123966942


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met

Jaccard Similarity: 0.9758873166473836
Classification Report:
              precision    recall  f1-score   support

       T1424       1.00      0.98      0.99        44
       T1604       0.98      1.00      0.99        63
       T1532       0.97      0.98      0.98       101
       T1404       1.00      0.99      0.99       225
       T1422       0.99      0.99      0.99       546
       T1577       1.00      1.00      1.00        26
       T1437       1.00      0.98      0.99       500
       T1512       0.99      0.99      0.99       521
       T1430       0.99      0.99      0.99       600
       T1418       0.99      0.99      0.99       564
       T1624       1.00      1.00      1.00        26
       T1645       0.99      0.99      0.99       280
       T1429       0.99      0.99      0.99       569
       T1417       0.99      1.00      0.99       260
       T1481       0.95      1.00      0.98        41
       T1426       0.99      0.99      0.99       611
       T1644       

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))




********** Random Seed: 98 **********


Evaluating Label Powerset
Accuracy: 0.9645808736717828
Macro F1 Score: 0.9827549949224049
Weighted F1 score: 0.990249425570572
Micro F1 score: 0.9902349579975268
Macro Precision: 0.9829039463717294
Weighted Precision: 0.9921611899745085
Micro Precision: 0.992053998632946
Macro Recall: 0.9834298615869725
Weighted Recall: 0.9884225759768451
Micro Recall: 0.9884225759768451
Hamming Loss: 0.005632624950806769
Zero One Loss: 0.0354191263282172
Jaccard Similarity: 0.9762592210318644


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Classification Report:
              precision    recall  f1-score   support

       T1424       1.00      1.00      1.00        47
       T1604       0.99      1.00      0.99        67
       T1532       0.96      0.98      0.97        84
       T1404       0.99      0.99      0.99       204
       T1422       0.99      0.99      0.99       551
       T1577       1.00      1.00      1.00        15
       T1437       1.00      0.98      0.99       494
       T1512       1.00      0.98      0.99       529
       T1430       0.99      0.99      0.99       602
       T1418       1.00      0.98      0.99       568
       T1624       1.00      1.00      1.00        15
       T1645       1.00      0.99      1.00       271
       T1429       1.00      0.99      0.99       569
       T1417       0.98      0.98      0.98       262
       T1481       0.87      0.94      0.90        35
       T1426       1.00      0.99      0.99       620
       T1644       1.00      0.99      1.00       418
    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))




********** Random Seed: 262 **********


Evaluating Label Powerset
Accuracy: 0.9669421487603306
Macro F1 Score: 0.9847688310092622
Weighted F1 score: 0.9894977640914842
Micro F1 score: 0.9894763642535856
Macro Precision: 0.9793818106972906
Weighted Precision: 0.9864163750257836
Micro Precision: 0.986295575670417
Macro Recall: 0.9906570631989768
Weighted Recall: 0.9926777352064708
Micro Recall: 0.9926777352064708
Hamming Loss: 0.006099960645415191
Zero One Loss: 0.03305785123966942
Jaccard Similarity: 0.9761638425881792
Classification Report:
              precision    recall  f1-score   support

       T1424       0.96      0.98      0.97        51
       T1604       1.00      1.00      1.00        71
       T1532       0.96      0.97      0.96        92
       T1404       0.99      0.99      0.99       223
       T1422       0.99      1.00      0.99       529
       T1577       1.00      1.00      1.00        25
       T1437       0.99      0.99      0.99       493
       T1512     

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 354 **********


Evaluating Label Powerset
Accuracy: 0.9775678866587958
Macro F1 Score: 0.9911955498333213
Weighted F1 score: 0.9936010535342295
Micro F1 score: 0.9935892028679882
Macro Precision: 0.988279621415463
Weighted Precision: 0.9929790219690534
Micro Precision: 0.9929191604147349
Macro Recall: 0.9943160379803629
Weighted Recall: 0.9942601502490082
Micro Recall: 0.9942601502490082
Hamming Loss: 0.003738685556867375
Zero One Loss: 0.022432113341204207


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met

Jaccard Similarity: 0.9834798130535003
Classification Report:
              precision    recall  f1-score   support

       T1424       0.98      0.98      0.98        47
       T1604       1.00      1.00      1.00        69
       T1532       0.98      0.97      0.98       108
       T1404       1.00      1.00      1.00       214
       T1422       1.00      0.99      1.00       548
       T1577       1.00      1.00      1.00        31
       T1437       1.00      0.99      0.99       499
       T1512       0.99      1.00      1.00       510
       T1430       0.99      0.99      0.99       601
       T1418       0.99      0.99      0.99       561
       T1624       1.00      1.00      1.00        31
       T1645       1.00      0.99      0.99       280
       T1429       0.99      1.00      1.00       559
       T1417       0.99      0.99      0.99       269
       T1481       0.92      1.00      0.96        35
       T1426       0.99      0.99      0.99       610
       T1644       

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 560 **********


Evaluating Label Powerset
Accuracy: 0.9539551357733176
Macro F1 Score: 0.9777509633464739
Weighted F1 score: 0.9844457106992596
Micro F1 score: 0.9844397463002115
Macro Precision: 0.9736412431851704
Weighted Precision: 0.9811259562207032
Micro Precision: 0.9810382605764368
Macro Recall: 0.9821808453510498
Weighted Recall: 0.9878649015614392
Micro Recall: 0.9878649015614392
Hamming Loss: 0.00905155450609996
Zero One Loss: 0.046044864226682414
Jaccard Similarity: 0.9645640911394154
Classification Report:
              precision    recall  f1-score   support

       T1424       0.95      0.93      0.94        42
       T1604       0.98      1.00      0.99        55
       T1532       0.96      0.98      0.97        98
       T1404       0.97      0.99      0.98       212
       T1422       0.98      0.99      0.98       526
       T1577       1.00      1.00      1.00        28
       T1437       0.98      0.99      0.99       493
       T1512    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))




********** Random Seed: 1600 **********


Evaluating Label Powerset
Accuracy: 0.9634002361275088
Macro F1 Score: 0.9818659237026005
Weighted F1 score: 0.9892099576180525
Micro F1 score: 0.9891907930990632
Macro Precision: 0.9773179814898301
Weighted Precision: 0.9865501360607695
Micro Precision: 0.9863893820272213
Macro Recall: 0.9871570745697685
Weighted Recall: 0.9920081618772317
Micro Recall: 0.9920081618772317
Hamming Loss: 0.006272136953955136
Zero One Loss: 0.0365997638724912
Jaccard Similarity: 0.9721101887972029


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Classification Report:
              precision    recall  f1-score   support

       T1424       0.94      1.00      0.97        51
       T1604       1.00      1.00      1.00        61
       T1532       0.93      0.97      0.95        78
       T1404       1.00      1.00      1.00       229
       T1422       0.99      0.99      0.99       525
       T1577       1.00      1.00      1.00        11
       T1437       0.99      0.99      0.99       494
       T1512       1.00      0.99      1.00       521
       T1430       0.99      0.99      0.99       600
       T1418       0.99      0.99      0.99       566
       T1624       1.00      1.00      1.00        11
       T1645       0.99      1.00      1.00       287
       T1429       0.99      0.99      0.99       566
       T1417       0.99      0.99      0.99       254
       T1481       1.00      0.84      0.91        37
       T1426       0.99      0.99      0.99       611
       T1644       0.99      0.99      0.99       411
    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 42 **********


Evaluating Label Powerset
Accuracy: 0.9761904761904762
Macro F1 Score: 0.9886112540672644
Weighted F1 score: 0.9915130147769058
Micro F1 score: 0.991501200503068
Macro Precision: 0.9856751529277691
Weighted Precision: 0.9898626981001943
Micro Precision: 0.9898036828488814
Macro Recall: 0.9916722497837259
Weighted Recall: 0.9932045506604565
Micro Recall: 0.9932045506604565
Hamming Loss: 0.004809351276742581
Zero One Loss: 0.023809523809523836
Jaccard Similarity: 0.9809127880005722
Classification Report:
              precision    recall  f1-score   support

       T1424       0.98      1.00      0.99        40
       T1604       0.99      0.97      0.98        89
       T1532       0.96      0.98      0.97       129
       T1404       0.99      0.99      0.99       223
       T1422       0.99      0.99      0.99       616
       T1577       1.00      1.00      1.00        34
       T1437       0.99      0.99      0.99       560
       T1512     

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 1433 **********


Evaluating Label Powerset
Accuracy: 0.9606625258799172
Macro F1 Score: 0.9834161418395341
Weighted F1 score: 0.9880569053609732
Micro F1 score: 0.9880088355948249
Macro Precision: 0.9760323867731527
Weighted Precision: 0.9840945606746953
Micro Precision: 0.9838950428156179
Macro Recall: 0.9912751350399712
Weighted Recall: 0.9921571734136101
Micro Recall: 0.9921571734136101
Hamming Loss: 0.006556245686680469
Zero One Loss: 0.039337474120082816
Jaccard Similarity: 0.9668256313277159
Classification Report:
              precision    recall  f1-score   support

       T1424       0.97      1.00      0.99        37
       T1604       1.00      1.00      1.00        89
       T1532       0.95      0.96      0.96       122
       T1404       0.98      1.00      0.99       201
       T1422       0.99      0.99      0.99       606
       T1577       1.00      1.00      1.00        29
       T1437       0.99      0.99      0.99       529
       T1512  

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 2396 **********


Evaluating Label Powerset
Accuracy: 0.9710144927536232
Macro F1 Score: 0.9883775368470141
Weighted F1 score: 0.9901244966394295
Micro F1 score: 0.9901310595294489
Macro Precision: 0.9888161308935098
Weighted Precision: 0.9897029130236117
Micro Precision: 0.9896622474747475
Macro Recall: 0.9881140324371614
Weighted Recall: 0.9906003159557661
Micro Recall: 0.9906003159557661
Hamming Loss: 0.005391649413388544
Zero One Loss: 0.02898550724637683
Jaccard Similarity: 0.9764500060206246
Classification Report:
              precision    recall  f1-score   support

       T1424       0.97      1.00      0.98        56
       T1604       0.96      1.00      0.98        68
       T1532       0.97      0.98      0.98       114
       T1404       0.98      0.97      0.98       193
       T1422       0.99      0.99      0.99       586
       T1577       1.00      1.00      1.00        26
       T1437       0.99      0.99      0.99       488
       T1512   

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 451 **********


Evaluating Label Powerset
Accuracy: 0.9730848861283644
Macro F1 Score: 0.9860583485406317
Weighted F1 score: 0.9908184956681533
Micro F1 score: 0.9908228460793804
Macro Precision: 0.9830816495286866
Weighted Precision: 0.9893540739492617
Micro Precision: 0.9893287967831735
Macro Recall: 0.9892281765369804
Weighted Recall: 0.9923214147211665
Micro Recall: 0.9923214147211665
Hamming Loss: 0.00511128364389234
Zero One Loss: 0.026915113871635588
Jaccard Similarity: 0.9774635010026478
Classification Report:
              precision    recall  f1-score   support

       T1424       0.98      0.98      0.98        48
       T1604       1.00      1.00      1.00        83
       T1532       0.97      0.98      0.97       123
       T1404       1.00      0.99      0.99       206
       T1422       0.99      1.00      0.99       606
       T1577       0.97      1.00      0.98        29
       T1437       0.99      1.00      0.99       546
       T1512    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 995 **********


Evaluating Label Powerset
Accuracy: 0.968944099378882
Macro F1 Score: 0.9864761479235931
Weighted F1 score: 0.9920043144076626
Micro F1 score: 0.992
Macro Precision: 0.9831304211066229
Weighted Precision: 0.9892541165989021
Micro Precision: 0.9892113660537912
Macro Recall: 0.98998036620341
Weighted Recall: 0.9948044009779952
Micro Recall: 0.9948044009779952
Hamming Loss: 0.004528985507246377
Zero One Loss: 0.03105590062111796
Jaccard Similarity: 0.9760061156541489
Classification Report:
              precision    recall  f1-score   support

       T1424       0.94      0.98      0.96        47
       T1604       1.00      0.99      0.99        76
       T1532       1.00      1.00      1.00       110
       T1404       0.98      1.00      0.99       240
       T1422       0.99      0.99      0.99       592
       T1577       1.00      1.00      1.00        34
       T1437       0.99      0.99      0.99       535
       T1512       0.99      0.9

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/me



********** Random Seed: 98 **********


Evaluating Label Powerset
Accuracy: 0.9658385093167702
Macro F1 Score: 0.9872257543881932
Weighted F1 score: 0.9913151407676642
Micro F1 score: 0.9913029973598385
Macro Precision: 0.9836829443577004
Weighted Precision: 0.9900083083489071
Micro Precision: 0.9899193548387096
Macro Recall: 0.9910082956513216
Weighted Recall: 0.9926905132192846
Micro Recall: 0.9926905132192846
Hamming Loss: 0.004830917874396135
Zero One Loss: 0.03416149068322982
Jaccard Similarity: 0.9744891382806503
Classification Report:
              precision    recall  f1-score   support

       T1424       0.95      1.00      0.97        39
       T1604       0.99      1.00      0.99        86
       T1532       0.98      0.98      0.98       128
       T1404       0.99      0.96      0.98       200
       T1422       0.99      1.00      0.99       605
       T1577       1.00      1.00      1.00        32
       T1437       0.99      1.00      0.99       528
       T1512     

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 262 **********


Evaluating Label Powerset
Accuracy: 0.9720496894409938
Macro F1 Score: 0.9888977166551999
Weighted F1 score: 0.990700718675142
Micro F1 score: 0.9906869319028461
Macro Precision: 0.982548379206842
Weighted Precision: 0.9852455204815074
Micro Precision: 0.9851818922723569
Macro Recall: 0.9955054959995383
Weighted Recall: 0.9962538398141905
Micro Recall: 0.9962538398141905
Hamming Loss: 0.005391649413388544
Zero One Loss: 0.02795031055900621


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met

Jaccard Similarity: 0.9779529053837747
Classification Report:
              precision    recall  f1-score   support

       T1424       1.00      1.00      1.00        47
       T1604       0.99      1.00      0.99        79
       T1532       0.96      0.98      0.97       125
       T1404       0.97      1.00      0.98       224
       T1422       0.98      0.99      0.99       615
       T1577       1.00      1.00      1.00        29
       T1437       0.99      1.00      1.00       533
       T1512       0.99      1.00      0.99       569
       T1430       0.99      1.00      0.99       684
       T1418       0.98      1.00      0.99       632
       T1624       1.00      1.00      1.00        29
       T1645       0.98      1.00      0.99       317
       T1429       0.99      1.00      0.99       627
       T1417       0.99      0.99      0.99       350
       T1481       0.94      0.98      0.96        45
       T1426       0.99      0.99      0.99       701
       T1644       

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 354 **********


Evaluating Label Powerset
Accuracy: 0.9554865424430642
Macro F1 Score: 0.9767919116408148
Weighted F1 score: 0.9845612464308564
Micro F1 score: 0.9845139527752224
Macro Precision: 0.9752439387898747
Weighted Precision: 0.9847080301899224
Micro Precision: 0.9844384821770793
Macro Recall: 0.9791574378862046
Weighted Recall: 0.984589434945948
Micro Recall: 0.984589434945948
Hamming Loss: 0.008712905452035886
Zero One Loss: 0.04451345755693581
Jaccard Similarity: 0.9623795592363278
Classification Report:
              precision    recall  f1-score   support

       T1424       0.80      1.00      0.89        41
       T1604       0.99      0.99      0.99        81
       T1532       0.99      0.96      0.97       148
       T1404       0.96      0.98      0.97       222
       T1422       0.99      0.98      0.99       625
       T1577       1.00      0.97      0.99        38
       T1437       0.98      0.98      0.98       518
       T1512      

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 560 **********


Evaluating Label Powerset
Accuracy: 0.9616977225672878
Macro F1 Score: 0.9812730160126515
Weighted F1 score: 0.987802337974181
Micro F1 score: 0.9878277857089188
Macro Precision: 0.9843893814506991
Weighted Precision: 0.9891755419629101
Micro Precision: 0.9891656007824844
Macro Recall: 0.9783515209714041
Weighted Recall: 0.986493584452615
Micro Recall: 0.986493584452615
Hamming Loss: 0.006987577639751553
Zero One Loss: 0.038302277432712195
Jaccard Similarity: 0.9705628601901893
Classification Report:
              precision    recall  f1-score   support

       T1424       0.98      0.98      0.98        44
       T1604       0.96      1.00      0.98        71
       T1532       0.99      0.99      0.99       126
       T1404       0.98      0.99      0.98       216
       T1422       0.99      0.99      0.99       620
       T1577       1.00      0.97      0.99        40
       T1437       0.99      0.99      0.99       541
       T1512      

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 1600 **********


Evaluating Label Powerset
Accuracy: 0.9699792960662525
Macro F1 Score: 0.9869998007255406
Weighted F1 score: 0.9911266878380287
Micro F1 score: 0.991132097201428
Macro Precision: 0.9836593986396508
Weighted Precision: 0.9873312939662535
Micro Precision: 0.9873040152963671
Macro Recall: 0.9905159227701564
Weighted Recall: 0.9949899799599199
Micro Recall: 0.9949899799599199
Hamming Loss: 0.004981884057971014
Zero One Loss: 0.03002070393374745
Jaccard Similarity: 0.9771835234582367
Classification Report:
              precision    recall  f1-score   support

       T1424       0.98      1.00      0.99        46
       T1604       1.00      1.00      1.00        66
       T1532       0.97      0.97      0.97       115
       T1404       0.99      0.99      0.99       211
       T1422       0.99      1.00      0.99       592
       T1577       0.97      1.00      0.98        30
       T1437       0.99      1.00      0.99       518
       T1512    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 42 **********


Evaluating Label Powerset
Accuracy: 0.9824723247232472
Macro F1 Score: 0.9919630117417126
Weighted F1 score: 0.9945518780553503
Micro F1 score: 0.99455547664942
Macro Precision: 0.9933613860285195
Weighted Precision: 0.9968371404062577
Micro Precision: 0.9968139913232104
Macro Recall: 0.9908714294649612
Weighted Recall: 0.9923071732235643
Micro Recall: 0.9923071732235643
Hamming Loss: 0.003094249692496925
Zero One Loss: 0.017527675276752808
Jaccard Similarity: 0.9861726119038113
Classification Report:
              precision    recall  f1-score   support

       T1424       0.97      1.00      0.98        56
       T1604       0.99      0.99      0.99        78
       T1532       0.99      0.98      0.99       148
       T1404       1.00      0.99      0.99       228
       T1422       1.00      0.99      0.99       688
       T1577       1.00      1.00      1.00        37
       T1437       0.99      0.99      0.99       577
       T1512      

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 1433 **********


Evaluating Label Powerset
Accuracy: 0.9677121771217713
Macro F1 Score: 0.9871266297061089
Weighted F1 score: 0.990923429200665
Micro F1 score: 0.9909192511874826
Macro Precision: 0.9851174025864066
Weighted Precision: 0.9898825540250548
Micro Precision: 0.9898130058610103
Macro Recall: 0.9894434260840147
Weighted Recall: 0.992027972027972
Micro Recall: 0.992027972027972
Hamming Loss: 0.0049969249692496925
Zero One Loss: 0.032287822878228734
Jaccard Similarity: 0.9709613402789834
Classification Report:
              precision    recall  f1-score   support

       T1424       0.98      1.00      0.99        46
       T1604       1.00      1.00      1.00        79
       T1532       0.95      0.99      0.97       140
       T1404       0.99      1.00      0.99       204
       T1422       0.99      1.00      0.99       639
       T1577       1.00      1.00      1.00        47
       T1437       0.99      1.00      0.99       540
       T1512    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/me



********** Random Seed: 2396 **********


Evaluating Label Powerset
Accuracy: 0.9621771217712177
Macro F1 Score: 0.9830130745524244
Weighted F1 score: 0.9870589813160006
Micro F1 score: 0.987053194483535
Macro Precision: 0.9814010775016997
Weighted Precision: 0.9870385207172712
Micro Precision: 0.9869837472736227
Macro Recall: 0.9847966266252678
Weighted Recall: 0.9871226514671733
Micro Recall: 0.9871226514671733
Hamming Loss: 0.007072570725707257
Zero One Loss: 0.037822878228782275
Jaccard Similarity: 0.9711747936452786


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met

Classification Report:
              precision    recall  f1-score   support

       T1424       0.93      0.98      0.96        58
       T1604       1.00      0.99      0.99        88
       T1532       0.98      0.99      0.99       155
       T1404       0.98      0.97      0.98       201
       T1422       0.99      0.99      0.99       681
       T1577       1.00      1.00      1.00        32
       T1437       0.99      0.99      0.99       554
       T1512       0.99      0.99      0.99       602
       T1430       0.99      0.99      0.99       741
       T1418       0.98      0.99      0.98       661
       T1624       1.00      1.00      1.00        32
       T1645       0.99      0.99      0.99       303
       T1429       0.99      0.99      0.99       683
       T1417       0.98      0.98      0.98       384
       T1481       0.95      0.95      0.95        62
       T1426       0.99      0.99      0.99       766
       T1644       0.99      0.98      0.99       460
    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 451 **********


Evaluating Label Powerset
Accuracy: 0.9714022140221402
Macro F1 Score: 0.9889938369528325
Weighted F1 score: 0.9916871236792968
Micro F1 score: 0.9916910877434925
Macro Precision: 0.9887034832263378
Weighted Precision: 0.9917414342603444
Micro Precision: 0.9917252792718245
Macro Recall: 0.9893726280027897
Weighted Recall: 0.9916568985727091
Micro Recall: 0.9916568985727091
Hamming Loss: 0.004631765067650676
Zero One Loss: 0.02859778597785978


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met

Jaccard Similarity: 0.9790555246347632
Classification Report:
              precision    recall  f1-score   support

       T1424       0.97      0.94      0.96        36
       T1604       0.99      0.99      0.99        88
       T1532       0.99      0.99      0.99       147
       T1404       0.99      0.99      0.99       218
       T1422       0.99      0.99      0.99       668
       T1577       1.00      1.00      1.00        39
       T1437       0.99      0.99      0.99       577
       T1512       1.00      1.00      1.00       603
       T1430       0.99      1.00      1.00       734
       T1418       0.99      0.99      0.99       679
       T1624       1.00      1.00      1.00        39
       T1645       1.00      0.99      1.00       326
       T1429       1.00      1.00      1.00       663
       T1417       0.99      1.00      0.99       415
       T1481       0.98      0.98      0.98        66
       T1426       0.99      1.00      0.99       751
       T1644       

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 995 **********


Evaluating Label Powerset
Accuracy: 0.9677121771217713
Macro F1 Score: 0.9863228137121741
Weighted F1 score: 0.9898253159830189
Micro F1 score: 0.9898429646063716
Macro Precision: 0.9866565865817426
Weighted Precision: 0.9890037104422033
Micro Precision: 0.9889173651035533
Macro Recall: 0.9864596348486611
Weighted Recall: 0.9907702984038862
Micro Recall: 0.9907702984038862
Hamming Loss: 0.005631150061500615
Zero One Loss: 0.032287822878228734
Jaccard Similarity: 0.9758471960214913


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met

Classification Report:
              precision    recall  f1-score   support

       T1424       0.92      0.98      0.95        48
       T1604       1.00      0.99      0.99        87
       T1532       0.95      0.99      0.97       137
       T1404       1.00      0.98      0.99       229
       T1422       0.99      0.99      0.99       652
       T1577       1.00      1.00      1.00        35
       T1437       0.99      1.00      0.99       569
       T1512       0.99      0.99      0.99       607
       T1430       0.99      1.00      0.99       741
       T1418       0.99      0.99      0.99       675
       T1624       1.00      1.00      1.00        35
       T1645       0.99      1.00      0.99       318
       T1429       0.99      0.99      0.99       676
       T1417       0.99      0.98      0.98       401
       T1481       1.00      0.85      0.92        61
       T1426       0.99      0.99      0.99       748
       T1644       0.99      1.00      0.99       472
    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 98 **********


Evaluating Label Powerset
Accuracy: 0.9686346863468634
Macro F1 Score: 0.9888014872742948
Weighted F1 score: 0.9916111119686467
Micro F1 score: 0.991601909607276
Macro Precision: 0.9869787140072755
Weighted Precision: 0.9924572946403216
Micro Precision: 0.9923972937155612
Macro Recall: 0.9907897595721108
Weighted Recall: 0.990807799442897
Micro Recall: 0.990807799442897
Hamming Loss: 0.004631765067650676
Zero One Loss: 0.03136531365313655
Jaccard Similarity: 0.9780010319539356
Classification Report:
              precision    recall  f1-score   support

       T1424       1.00      1.00      1.00        40
       T1604       1.00      1.00      1.00        85
       T1532       0.98      0.98      0.98       133
       T1404       0.99      0.98      0.98       215
       T1422       0.99      0.99      0.99       676
       T1577       0.98      1.00      0.99        40
       T1437       0.99      0.99      0.99       560
       T1512       1

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Multilabel Confusion Matrix:
[[[1044    0]
  [   0   40]]

 [[ 999    0]
  [   0   85]]

 [[ 949    2]
  [   2  131]]

 [[ 866    3]
  [   5  210]]

 [[ 404    4]
  [   5  671]]

 [[1043    1]
  [   0   40]]

 [[ 519    5]
  [   5  555]]

 [[ 472    2]
  [   6  604]]

 [[ 340    2]
  [   4  738]]

 [[ 402    6]
  [   7  669]]

 [[1043    1]
  [   0   40]]

 [[ 773    4]
  [   2  305]]

 [[ 417    3]
  [   4  660]]

 [[ 661    5]
  [   3  415]]

 [[1029    3]
  [   1   51]]

 [[ 334    3]
  [   4  743]]

 [[ 601    3]
  [   4  476]]

 [[1023    1]
  [   0   60]]

 [[ 985    1]
  [   2   96]]

 [[ 815    6]
  [   3  260]]

 [[ 469    3]
  [   9  603]]

 [[ 955    1]
  [   2  126]]

 [[1038    2]
  [   2   42]]

 [[ 985    1]
  [   0   98]]

 [[ 636    2]
  [   7  439]]

 [[ 942    0]
  [   3  139]]

 [[ 985    1]
  [   0   98]]

 [[1038    1]
  [   0   45]]

 [[ 664    3]
  [   3  414]]

 [[ 973    4]
  [   2  105]]

 [[ 966    1]
  [   1  116]]

 [[ 979    2]
  [   0  103]]

 [[ 495    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 262 **********


Evaluating Label Powerset
Accuracy: 0.9714022140221402
Macro F1 Score: 0.9883991122430235
Weighted F1 score: 0.9907340145986498
Micro F1 score: 0.9907296860734602
Macro Precision: 0.9850710977545053
Weighted Precision: 0.9877315572677257
Micro Precision: 0.9876776587551634
Macro Recall: 0.9918699929230396
Weighted Recall: 0.9938006340260656
Micro Recall: 0.9938006340260656
Hamming Loss: 0.00507380073800738
Zero One Loss: 0.02859778597785978
Jaccard Similarity: 0.9731043828385442
Classification Report:
              precision    recall  f1-score   support

       T1424       0.96      0.96      0.96        47
       T1604       1.00      1.00      1.00        88
       T1532       0.95      1.00      0.97       117
       T1404       0.98      0.99      0.99       239
       T1422       0.99      1.00      0.99       657
       T1577       1.00      1.00      1.00        30
       T1437       0.99      0.99      0.99       540
       T1512     

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/me



********** Random Seed: 354 **********


Evaluating Label Powerset
Accuracy: 0.9760147601476015
Macro F1 Score: 0.9903693342919876
Weighted F1 score: 0.9929788535646874
Micro F1 score: 0.9929689888251079
Macro Precision: 0.9873032735701205
Weighted Precision: 0.9914270881005971
Micro Precision: 0.9913863266413456
Macro Recall: 0.9935376295384434
Weighted Recall: 0.9945567122542015
Micro Recall: 0.9945567122542015
Hamming Loss: 0.003978321033210332
Zero One Loss: 0.023985239852398532
Jaccard Similarity: 0.9781938664895307


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Classification Report:
              precision    recall  f1-score   support

       T1424       0.98      1.00      0.99        46
       T1604       0.97      0.98      0.97        91
       T1532       0.99      1.00      1.00       139
       T1404       0.98      0.99      0.99       238
       T1422       1.00      1.00      1.00       688
       T1577       1.00      1.00      1.00        37
       T1437       0.99      0.99      0.99       566
       T1512       1.00      0.99      1.00       628
       T1430       0.99      1.00      1.00       755
       T1418       0.99      1.00      0.99       689
       T1624       1.00      1.00      1.00        37
       T1645       0.99      1.00      1.00       349
       T1429       1.00      0.99      0.99       685
       T1417       0.98      1.00      0.99       407
       T1481       0.98      1.00      0.99        63
       T1426       0.99      1.00      1.00       767
       T1644       0.99      0.99      0.99       486
    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 560 **********


Evaluating Label Powerset
Accuracy: 0.9686346863468634
Macro F1 Score: 0.9834489232319652
Weighted F1 score: 0.9899751783791849
Micro F1 score: 0.9899702566230891
Macro Precision: 0.9810258772955217
Weighted Precision: 0.9879318359432302
Micro Precision: 0.9878520154610713
Macro Recall: 0.9867850103336252
Weighted Recall: 0.992097601552752
Micro Recall: 0.992097601552752
Hamming Loss: 0.005573493234932349
Zero One Loss: 0.03136531365313655
Jaccard Similarity: 0.9720965991958502


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Classification Report:
              precision    recall  f1-score   support

       T1424       1.00      0.94      0.97        51
       T1604       0.95      1.00      0.97        75
       T1532       0.99      0.98      0.98       164
       T1404       0.99      0.99      0.99       203
       T1422       0.99      0.99      0.99       680
       T1577       1.00      1.00      1.00        41
       T1437       0.99      0.99      0.99       553
       T1512       0.99      1.00      0.99       616
       T1430       0.99      0.99      0.99       755
       T1418       0.99      0.99      0.99       697
       T1624       1.00      1.00      1.00        41
       T1645       0.99      1.00      1.00       308
       T1429       0.99      0.99      0.99       692
       T1417       0.99      1.00      0.99       402
       T1481       0.96      0.91      0.94        58
       T1426       0.99      0.99      0.99       773
       T1644       0.99      1.00      0.99       459
    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 in samples with no true or predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/met



********** Random Seed: 1600 **********


Evaluating Label Powerset
Accuracy: 0.9714022140221402
Macro F1 Score: 0.9891066078605372
Weighted F1 score: 0.9916411327134794
Micro F1 score: 0.9916279724215562
Macro Precision: 0.9859052104142022
Weighted Precision: 0.9904663823642154
Micro Precision: 0.9903738055087128
Macro Recall: 0.992571985675772
Weighted Recall: 0.9928853198083968
Micro Recall: 0.9928853198083968
Hamming Loss: 0.0045741082410824105
Zero One Loss: 0.02859778597785978
Jaccard Similarity: 0.9723891093952955
Classification Report:
              precision    recall  f1-score   support

       T1424       0.94      1.00      0.97        46
       T1604       0.99      1.00      0.99        82
       T1532       0.94      1.00      0.97       136
       T1404       1.00      0.99      0.99       216
       T1422       0.99      0.99      0.99       657
       T1577       1.00      1.00      1.00        35
       T1437       0.99      0.99      0.99       543
       T1512   

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
